//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.01 at 02:41:35 PM CEST 
//


package io.glebtanaka.currency_converter.wsdl;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.glebtanaka.currency_converter.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.glebtanaka.currency_converter.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CurrencyConversionRequest }
     * 
     */
    public CurrencyConversionRequest createCurrencyConversionRequest() {
        return new CurrencyConversionRequest();
    }

    /**
     * Create an instance of {@link CurrencyConversionResponse }
     * 
     */
    public CurrencyConversionResponse createCurrencyConversionResponse() {
        return new CurrencyConversionResponse();
    }

    /**
     * Create an instance of {@link GetCurrenciesRequest }
     * 
     */
    public GetCurrenciesRequest createGetCurrenciesRequest() {
        return new GetCurrenciesRequest();
    }

    /**
     * Create an instance of {@link GetCurrenciesResponse }
     * 
     */
    public GetCurrenciesResponse createGetCurrenciesResponse() {
        return new GetCurrenciesResponse();
    }

}
