//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.01 at 02:41:35 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://glebtanaka.io/currency-converter", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.glebtanaka.currency_converter.wsdl;
